Repository go-ldap/ldap, pull requests merged in 2024-04, with the labels that each got.

#497 feat: Refactor `ParseDN` function to fix resource usage and invalid parsings (fixes #487)
  dn.go
  dn_test.go
  ldap.go
  v3/dn.go
  v3/dn_test.go
  v3/ldap.go
Labels: bug, enhancement

#504 Add tests to parseDN (fuzzing, roundtrip ...)
  dn.go
  dn_test.go
  fuzz_test.go
  v3/dn.go
  v3/dn_test.go
Labels: enhancement

#505 fix: Replace DER with ASN1 BER encoding when parsing distinguishedNames
  dn.go
  dn_test.go
  v3/dn.go
  v3/dn_test.go
Labels: enhancement

#508 Revert #499: Mark public Start function as deprecated
  conn.go
  v3/conn.go
Labels: bug
